---

- name: Ensure Jenkins Container
  community.docker.docker_container:
    name: jenkins-master
    hostname: jenkins-master.local
    image: jenkins/jenkins:lts
    networks_cli_compatible: false
    container_default_behavior: no_defaults
    auto_remove: yes
    networks:
      - name: ops_tools_net
    ports:
      - '9020:9020' # Web UI
      - '50000:50000' # Remote API
      - '53801:53801' # Random SSH Port
    volumes:
      #- jenkins-docker-certs:/certs/client
      - ./roles/jenkins/volumes/data/:/var/jenkins_home
    env:
      JENKINS_OPTS: '--httpPort=9020'
