---

- name: Ensure OpenLDAP Container
  community.docker.docker_container:
    name: openldap
    hostname: openldap.local
    image: openmicroscopy/apacheds:latest
    networks_cli_compatible: false
    container_default_behavior: no_defaults
    auto_remove: yes
    networks:
      - name: ops_tools_net
    ports:
      - '10389:10389' # LDAP port
      - '60088:60088' # Kerberos
    volumes:
      - ./roles/openldap/volumes/data/:/var/lib/apacheds/
