---

- name: Ensure Keycloak Docker Volumes
  community.docker.docker_volume:
    name: keycloak-config

- name: Ensure Keycloak Container
  community.docker.docker_container:
    name: keycloak
    hostname: keycloak.local
    image: quay.io/keycloak/keycloak:12.0.3
    networks_cli_compatible: false
    container_default_behavior: no_defaults
    auto_remove: yes
    networks:
      - name: ops_tools_net
    ports:
      - '8090:8080' # Web UI
      - '8443:8443' # Web UI
    volumes:
      - keycloak-config:/opt/jboss/keycloak/standalone/configuration
    env:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

