---

- name: Ensure Keycloak Container
  community.docker.docker_container:
    name: keycloak
    hostname: keycloak.local
    image: quay.io/keycloak/keycloak:latest
    networks_cli_compatible: false
    container_default_behavior: no_defaults
    auto_remove: yes
    networks:
      - name: ops_tools_net
    ports:
      - '8080:8080' # Web UI
      - '8443:8443' # Web UI
    volumes:
      - ./roles/keycloak/volumes/data/:/opt/jboss/keycloak/standalone/data
      - ./roles/keycloak/volumes/config/:/opt/jboss/keycloak/standalone/configuration
    env:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      KEYCLOAK_HTTP_PORT: '8080'
